//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactData
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string AccountNo { get; set; }
        public Nullable<double> ExpectAmt { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid UserDataId { get; set; }
    }
}
