//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventEntity
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public short Type { get; set; }
        public short EventCat { get; set; }
        public string EventAt { get; set; }
        public string EventOn { get; set; }
        public Nullable<bool> Recurring { get; set; }
        public System.Guid UserDataId { get; set; }
    }
}
