//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionEnity
    {
        public System.Guid Id { get; set; }
        public double Amount { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid UserDataId { get; set; }
        public System.Guid ContactDataId { get; set; }
    }
}
